name: Find LaunchDarkly feature flags

on: pull_request

permissions:
  pull-requests: write

jobs:
  find-flags:
    runs-on: ubuntu-latest
    name: Find flags in diff
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Find flags
        uses: launchdarkly/find-code-references-in-pull-request@v2
        id: find-flags
        with:
          project-key: default
          environment-key: test
          access-token: ${{ secrets.LAUNCHDARKLY_ACCESS_TOKEN }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
